services:
  backend:
    image: ghcr.io/sageseekersociety/cheese-backend-dev:dev
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
      es:
        condition: service_healthy
