services:
  frontend:
    image: ghcr.io/sageseekersociety/cheese-frontend:dev
    env_file: .env
    depends_on:
      - backend
    ports:
      - "4173:80"

  backend:
    image: ghcr.io/sageseekersociety/cheese-backend:dev
    env_file: .env
    volumes:
      - type: volume
        source: cheese_backend_uploads
        target: /app/uploads
    depends_on:
      database:
        condition: service_healthy
      es:
        condition: service_healthy
    ports:
      - "4174:3000"

  database:
    image: postgres:16.2
    env_file: .env
    volumes:
      - type: volume
        source: cheese_db_pg
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      start_period: 180s
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 3

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    env_file: .env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ELASTICSEARCH_AUTH_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 4g
    volumes:
      - type: volume
        source: cheese_es
        target: /usr/share/elasticsearch/data
    ports:
      - '127.0.0.1:9200:9200'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -s --user elastic:${ELASTICSEARCH_AUTH_PASSWORD} -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -E 'green|yello'",
        ]
      start_period: 180s
      start_interval: 5s
      interval: 1m
      timeout: 10s
      retries: 3

  valkey:
    image: valkey/valkey:8.0.2
    env_file: .env
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  cheese_backend_uploads:
  cheese_db_pg:
  cheese_es:
