services:
  backend:
    image: ghcr.io/sageseekersociety/cheese-backend-dev:dev
    build:
      context: .
      target: dev
    env_file: .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: pnpm-lock.yaml
    depends_on:
      database:
        condition: service_healthy
      es:
        condition: service_healthy
