services:
  backend:
    image: cheese_backend_dev
    build:
      context: .
      target: dev
    env_file: .env
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: pnpm-lock.yaml
    depends_on:
      database:
        condition: service_healthy
    
  database:
    image: postgres:16.2
    env_file: .env
    volumes:
      - type: volume
        source: cheese_db_pg
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      start_period: 30s
      start_interval: 3s
      interval: 5m
      timeout: 10s
      retries: 10

volumes:
  cheese_db_pg:
