/*
 *  DO NOT MODIFY THIS FILE!
 *
 *  TypeORM is deprecated in this project, and we use Prisma instead.
 *  This file is only used by legacy code.
 *
 *  A .legacy.prisma file with same schema is generated by Prisma.
 *  If you modify this file, the schema in .legacy.prisma will be inconsistent
 *  with this file. This may cause unexpected errors.
 *
 *  Also, because TypeORM will alter the database schema automatically if
 *  'syncronize' is set to true, modifying this file is extremely dangerous.
 *
 *  2024-02-19 by Nictheboy <nictheboy@outlook.com>
 *
 */

import { CommentCommentabletypeEnum } from '@prisma/client';
import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  Index,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

@Entity()
export class Comment {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({
    type: 'enum',
    enum: CommentCommentabletypeEnum,
  })
  commentableType: CommentCommentabletypeEnum;

  @Column()
  @Index()
  commentableId: number;

  @Column('text')
  content: string;

  @Column()
  @Index()
  createdById: number;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @DeleteDateColumn()
  deletedAt?: Date;
}

@Entity()
export class CommentDeleteLog {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Comment)
  comment: Comment;

  @Column()
  @Index()
  commentId: number;

  @Column()
  @Index()
  operatedById: number;

  @CreateDateColumn()
  createdAt: Date;
}

@Entity()
export class CommentQueryLog {
  @PrimaryGeneratedColumn()
  id: number;

  @ManyToOne(() => Comment)
  comment: Comment;

  @Column()
  @Index()
  commentId: number;

  @Column('int', { nullable: true })
  @Index()
  viewerId?: number | null;

  @Column()
  ip: string;

  @Column()
  userAgent: string = '';

  @CreateDateColumn()
  createdAt: Date;
}
