/*
 *  DO NOT MODIFY THIS FILE!
 *
 *  TypeORM is deprecated in this project, and we use Prisma instead.
 *  This file is only used by legacy code.
 *
 *  A .legacy.prisma file with same schema is generated by Prisma.
 *  If you modify this file, the schema in .legacy.prisma will be inconsistent
 *  with this file. This may cause unexpected errors.
 *
 *  Also, because TypeORM will alter the database schema automatically if
 *  'syncronize' is set to true, modifying this file is extremely dangerous.
 *
 *  2024-02-19 by Nictheboy <nictheboy@outlook.com>
 *
 */

/*
 *  Description: This file defines the database entities used for session.
 *
 *  Author(s):
 *      Nictheboy Li    <nictheboy@outlook.com>
 *
 */

import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity()
export class Session {
  @PrimaryGeneratedColumn()
  id: number;

  // If now > validUntil, the session is invalid.
  @Column()
  @Index()
  validUntil: Date;

  // If revoked == true, the session is invalid.
  @Column()
  revoked: boolean = false;

  // We can use this column to select all sessions of a user.
  @Column()
  @Index()
  userId: number;

  // JSON of Authorization object
  // It might be lengthy, so we uses "text",
  // which has no length limit.
  @Column('text')
  authorization: string;

  // If the sign time of a refreshToken < lastRefreshedAt,
  // the refreshToken is invalid.
  //
  // This means that a refreshToken can only be used once.
  //
  // This column is stored as integer timestamp, because
  // database does not support millisecond precision.
  // int32 is not enough, so we use int64.
  @Column('bigint')
  lastRefreshedAt: number;

  @CreateDateColumn()
  createdAt: Date;
}

@Entity()
export class SessionRefreshLog {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  sessionId: number;

  @Column('text')
  oldRefreshToken: string;

  @Column('text')
  newRefreshToken: string;

  @Column('text')
  accessToken: string;

  @CreateDateColumn()
  createdAt: Date;
}
