# This file is a modified version of .github/workflows/test.yml

name: Automatic Test Coverage

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      # only one run
      matrix:
        # See supported MySQL versions at https://hub.docker.com/_/mysql
        mysql-version: [latest]
        node-version: [18.x]
        pnpm-version: [8]

    env:
      DB_TYPE: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_USERNAME: testuser
      DB_PASSWORD: mysql-test-password
      DB_NAME: cheese
      DB_SYNCHRONIZE: true
      DB_AUTO_LOAD_ENTITIES: true
      DB_CONNECT_TIMEOUT: 60000
      DB_LOGGING: false
      JWT_SECRET: Test JWT Secret
      TEST_REPEAT: 10 # Tests will be repeated

    services:
      mysql: # See: https://joshi-aparna.github.io/blog/github-actions-mysql/
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USERNAME }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Start Application to Create Tables
        run: |
          PORT=7777
          pnpm start | tee output &
          while true; do
              if grep -q "Nest application successfully started" output; then
                  echo "Detected 'Nest application successfully started'. Stopping pnpm..."
                  pid=$(netstat -nlp | grep :$PORT | awk '{print $7}' | awk -F'/' '{print $1}')
                  kill $pid
                  break
              fi
              sleep 1
          done

      - name: Run Tests
        run: |
          for i in {1..${{ env.TEST_REPEAT }}}; do
            echo "Repeating Test [$i]"
            pnpm test:cov --verbose
          done